name: gym_max_tracker
description: A simple app to track your gym max weights

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Local database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Charts
  fl_chart: ^0.65.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true